### ISSUE TITLE
Existing session refuses to auto join in Chrome Canary 57

### ISSUE THREAD

**Issue by gscragg** [googlecast/CastVideos-chrome-sdk#30]
I have noticed in my custom player that auto rejoin after page reload is no longer working.
I pulled this repo down and it has the same problem in Canary.
The rejoin system works in Chrome 55.

Does this mean in newer versions of chrome the version of the SDK this sample uses will not work, and we need to update to v3?

Thanks.

**Comment by entertailion** [comment]
If you believe you have found a bug in the Cast SDK, then file an issue: https://code.google.com/p/google-cast-sdk/issues/list
